version: '3'
services:
  my-dev:
    # サービス名はプロジェクトや使用技術に合わせて変更してください
    build: .
    volumes:
      - ./data:/home/dev
    ports:
      - "8000:8000" # コンテナがリッスンするポートに応じて変更してください
    environment:
      - PYTHONUNBUFFERED=1
